apiVersion: v1
kind: PersistentVolume
metadata:
  name: mo-data-pv
  namespace: qfaas
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /home/ubuntu/mongopv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem